export enum Permission {
  // Kullanıcı Yönetimi
  USER_LIST = 'USER_LIST',
  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_SOFT_DELETE = 'USER_SOFT_DELETE',
  USER_ASSIGN_ROLE = 'USER_ASSIGN_ROLE',

  // Rol & Yetki Yönetimi
  ROLE_LIST = 'ROLE_LIST',
  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_MANAGE_PERMISSIONS = 'ROLE_MANAGE_PERMISSIONS',

  // Üye Yönetimi
  MEMBER_LIST = 'MEMBER_LIST',
  MEMBER_VIEW = 'MEMBER_VIEW',
  MEMBER_CREATE_APPLICATION = 'MEMBER_CREATE_APPLICATION',
  /** Bekleyen üye başvuruları listesini görüntüleme (onay/red ayrı izinler) */
  MEMBER_APPLICATIONS_VIEW = 'MEMBER_APPLICATIONS_VIEW',
  MEMBER_APPROVE = 'MEMBER_APPROVE',
  MEMBER_REJECT = 'MEMBER_REJECT',
  MEMBER_UPDATE = 'MEMBER_UPDATE',
  MEMBER_STATUS_CHANGE = 'MEMBER_STATUS_CHANGE', // istifa / ihraç / pasif
  /** Üye hareket geçmişi (MemberHistory) listesi */
  MEMBER_HISTORY_VIEW = 'MEMBER_HISTORY_VIEW',
  MEMBER_LIST_BY_PROVINCE = 'MEMBER_LIST_BY_PROVINCE', // Belirli bir ildeki üyeleri görüntüleme (UserScope'daki provinceId'ye göre)

  // Şube / İl / İlçe Yönetimi
  REGION_LIST = 'REGION_LIST',
  BRANCH_MANAGE = 'BRANCH_MANAGE',
  BRANCH_ASSIGN_PRESIDENT = 'BRANCH_ASSIGN_PRESIDENT',

  // İçerik Yönetimi
  CONTENT_MANAGE = 'CONTENT_MANAGE', // haber/duyuru/etkinlik CRUD
  CONTENT_PUBLISH = 'CONTENT_PUBLISH',

  // Evrak & Doküman
  DOCUMENT_SYSTEM_ACCESS = 'DOCUMENT_SYSTEM_ACCESS',
  DOCUMENT_TEMPLATE_MANAGE = 'DOCUMENT_TEMPLATE_MANAGE',
  DOCUMENT_MEMBER_HISTORY_VIEW = 'DOCUMENT_MEMBER_HISTORY_VIEW',
  DOCUMENT_GENERATE_PDF = 'DOCUMENT_GENERATE_PDF',
  DOCUMENT_UPLOAD = 'DOCUMENT_UPLOAD',
  DOCUMENT_DOWNLOAD = 'DOCUMENT_DOWNLOAD',

  // Raporlar & Dashboard
  REPORT_GLOBAL_VIEW = 'REPORT_GLOBAL_VIEW',
  REPORT_REGION_VIEW = 'REPORT_REGION_VIEW',
  REPORT_MEMBER_STATUS_VIEW = 'REPORT_MEMBER_STATUS_VIEW',
  REPORT_DUES_VIEW = 'REPORT_DUES_VIEW',

  // Bildirim & İletişim — WhatsApp (detaylı)
  /** @deprecated Eski birleşik izin; tüm WhatsApp alt izinlerine eşdeğer */
  WHATSAPP_ACCESS = 'WHATSAPP_ACCESS',
  /** Sohbet listesi, mesajları okuma, konuşma detayı, okundu işareti */
  WHATSAPP_CHAT_VIEW = 'WHATSAPP_CHAT_VIEW',
  /** Konuşmada / telefona mesaj gönderme */
  WHATSAPP_CHAT_SEND = 'WHATSAPP_CHAT_SEND',
  /** Konuşmayı arşivleme ve silme */
  WHATSAPP_CHAT_MANAGE = 'WHATSAPP_CHAT_MANAGE',
  /** Toplu WhatsApp gönderimi ve geçmiş */
  WHATSAPP_BULK_SEND = 'WHATSAPP_BULK_SEND',
  /** Otomatik şablonları listeleme */
  WHATSAPP_TEMPLATE_VIEW = 'WHATSAPP_TEMPLATE_VIEW',
  /** Şablon oluşturma / güncelleme / silme / şablonla gönderim */
  WHATSAPP_TEMPLATE_MANAGE = 'WHATSAPP_TEMPLATE_MANAGE',
  /** Oturum: QR, bağlan, bağlantıyı kes */
  WHATSAPP_INSTANCE_MANAGE = 'WHATSAPP_INSTANCE_MANAGE',

  NOTIFY_ALL_MEMBERS = 'NOTIFY_ALL_MEMBERS',
  NOTIFY_REGION = 'NOTIFY_REGION',
  NOTIFY_OWN_SCOPE = 'NOTIFY_OWN_SCOPE',

  // Sistem Ayarları & Loglar
  SYSTEM_SETTINGS_VIEW = 'SYSTEM_SETTINGS_VIEW',
  SYSTEM_SETTINGS_MANAGE = 'SYSTEM_SETTINGS_MANAGE',
  LOG_VIEW_ALL = 'LOG_VIEW_ALL',
  LOG_VIEW_OWN_SCOPE = 'LOG_VIEW_OWN_SCOPE',

  // Kurumlar (Institutions)
  INSTITUTION_LIST = 'INSTITUTION_LIST',
  INSTITUTION_VIEW = 'INSTITUTION_VIEW',
  INSTITUTION_CREATE = 'INSTITUTION_CREATE',
  INSTITUTION_UPDATE = 'INSTITUTION_UPDATE',
  INSTITUTION_APPROVE = 'INSTITUTION_APPROVE',

  // Meslekler
  PROFESSION_VIEW = 'PROFESSION_VIEW',
  PROFESSION_CREATE = 'PROFESSION_CREATE',
  PROFESSION_UPDATE = 'PROFESSION_UPDATE',
  PROFESSION_DELETE = 'PROFESSION_DELETE',

  // Tevkifat
  TEVKIFAT_VIEW = 'TEVKIFAT_VIEW',
  TEVKIFAT_EXPORT = 'TEVKIFAT_EXPORT',
  TEVKIFAT_TITLE_VIEW = 'TEVKIFAT_TITLE_VIEW',
  TEVKIFAT_TITLE_CREATE = 'TEVKIFAT_TITLE_CREATE',
  TEVKIFAT_TITLE_UPDATE = 'TEVKIFAT_TITLE_UPDATE',
  TEVKIFAT_TITLE_DELETE = 'TEVKIFAT_TITLE_DELETE',
  TEVKIFAT_CENTER_VIEW = 'TEVKIFAT_CENTER_VIEW',
  TEVKIFAT_CENTER_CREATE = 'TEVKIFAT_CENTER_CREATE',
  TEVKIFAT_CENTER_UPDATE = 'TEVKIFAT_CENTER_UPDATE',
  TEVKIFAT_CENTER_DELETE = 'TEVKIFAT_CENTER_DELETE',
  TEVKIFAT_FILE_UPLOAD = 'TEVKIFAT_FILE_UPLOAD',
  TEVKIFAT_FILE_APPROVE = 'TEVKIFAT_FILE_APPROVE',

  // Üye Kesintileri
  MEMBER_PAYMENT_ADD = 'MEMBER_PAYMENT_ADD', // Kesinti girişi (Muhasebe)
  MEMBER_PAYMENT_APPROVE = 'MEMBER_PAYMENT_APPROVE', // Kesinti onaylama (Admin)
  MEMBER_PAYMENT_LIST = 'MEMBER_PAYMENT_LIST', // Kesinti listesi görüntüleme
  MEMBER_PAYMENT_VIEW = 'MEMBER_PAYMENT_VIEW', // Kesinti detay görüntüleme

  // Onay Süreçleri
  APPROVAL_VIEW = 'APPROVAL_VIEW',
  APPROVAL_APPROVE = 'APPROVAL_APPROVE',
  APPROVAL_REJECT = 'APPROVAL_REJECT',

  // Panel Kullanıcı Başvuruları
  PANEL_USER_APPLICATION_CREATE = 'PANEL_USER_APPLICATION_CREATE',
  PANEL_USER_APPLICATION_LIST = 'PANEL_USER_APPLICATION_LIST',
  PANEL_USER_APPLICATION_VIEW = 'PANEL_USER_APPLICATION_VIEW',
  PANEL_USER_APPLICATION_APPROVE = 'PANEL_USER_APPLICATION_APPROVE',
  PANEL_USER_APPLICATION_REJECT = 'PANEL_USER_APPLICATION_REJECT',

  // Avans Sistemi
  ADVANCE_VIEW = 'ADVANCE_VIEW', // Avansları listele ve görüntüle
  ADVANCE_CREATE = 'ADVANCE_CREATE', // Yeni avans kaydı
  ADVANCE_UPDATE = 'ADVANCE_UPDATE', // Avans bilgilerini güncelle
  ADVANCE_DELETE = 'ADVANCE_DELETE', // Avansı sil
  /** Belge yükle, değiştir, kaldır (üye evraklarından ayır) */
  ADVANCE_DOCUMENT = 'ADVANCE_DOCUMENT',
  /**
   * @deprecated Eski birleşik avans izni. Hâlâ veritabanında kalan rollerde
   * tüm avans mutasyonlarına (CREATE/UPDATE/DELETE/DOCUMENT) eşdeğer.
   */
  ADVANCE_ADD = 'ADVANCE_ADD',

  // Fatura Sistemi
  INVOICE_VIEW = 'INVOICE_VIEW', // Faturaları listele ve görüntüle
  INVOICE_CREATE = 'INVOICE_CREATE', // Fatura oluştur
  INVOICE_UPDATE = 'INVOICE_UPDATE', // Fatura güncelle
  INVOICE_DELETE = 'INVOICE_DELETE', // Fatura sil
}
